hash-format = "sha256"

[[files]]
file = "datapacks/allthemons-x-mega-showdown-legacy.pw.toml"
metafile = true

[[files]]
file = "datapacks/cavscobblemons.pw.toml"
metafile = true

[[files]]
file = "datapacks/cobblemon-fast-mounts.pw.toml"
metafile = true

[[files]]
file = "datapacks/cobblemon-pokemans.pw.toml"
metafile = true

[[files]]
file = "datapacks/cobblemon-swirlix-and-slurpuff.pw.toml"
metafile = true

[[files]]
file = "datapacks/hydro-reanimodel-pack.pw.toml"
metafile = true

[[files]]
file = "datapacks/missingmons-cobblemon.pw.toml"
metafile = true

[[files]]
file = "datapacks/mundialmons.pw.toml"
metafile = true

[[files]]
file = "datapacks/mysticmons.pw.toml"
metafile = true

[[files]]
file = "datapacks/planeta-cobblemon-pokemon-pack.pw.toml"
metafile = true

[[files]]
file = "datapacks/pokecenter-pc-cobblemon.pw.toml"
metafile = true

[[files]]
file = "mods/accessories-compat-layer.pw.toml"
metafile = true

[[files]]
file = "mods/accessories.pw.toml"
metafile = true

[[files]]
file = "mods/advancement-plaques.pw.toml"
metafile = true

[[files]]
file = "mods/advancementdisable.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
metafile = true

[[files]]
file = "mods/beautify-refabricated.pw.toml"
metafile = true

[[files]]
file = "mods/better-beds.pw.toml"
metafile = true

[[files]]
file = "mods/better-f1-reborn.pw.toml"
metafile = true

[[files]]
file = "mods/better-nether-map.pw.toml"
metafile = true

[[files]]
file = "mods/better-third-person.pw.toml"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
metafile = true

[[files]]
file = "mods/biome-replacer.pw.toml"
metafile = true

[[files]]
file = "mods/brb.pw.toml"
metafile = true

[[files]]
file = "mods/carved-wood.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/cobblecuisine.pw.toml"
metafile = true

[[files]]
file = "mods/cobbledollars.pw.toml"
metafile = true

[[files]]
file = "mods/cobblefurnies.pw.toml"
metafile = true

[[files]]
file = "mods/cobblemon-additions.pw.toml"
metafile = true

[[files]]
file = "mods/cobblemon-badgebox.pw.toml"
metafile = true

[[files]]
file = "mods/cobblemon-capture-xp.pw.toml"
metafile = true

[[files]]
file = "mods/cobblemon-fight-or-flight-reborn.pw.toml"
metafile = true

[[files]]
file = "mods/cobblemon-journey-mounts.pw.toml"
metafile = true

[[files]]
file = "mods/cobblemon-mega-showdown.pw.toml"
metafile = true

[[files]]
file = "mods/cobblemon-pasture-loot.pw.toml"
metafile = true

[[files]]
file = "mods/cobblemon-playerxp.pw.toml"
metafile = true

[[files]]
file = "mods/cobblemon-pokenav.pw.toml"
metafile = true

[[files]]
file = "mods/cobblemon-safepastures.pw.toml"
metafile = true

[[files]]
file = "mods/cobblemon-tim-core.pw.toml"
metafile = true

[[files]]
file = "mods/cobblemon-ui-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/cobblemon.pw.toml"
metafile = true

[[files]]
file = "mods/cobbleverse-badges.pw.toml"
metafile = true

[[files]]
file = "mods/cobbreeding.pw.toml"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
metafile = true

[[files]]
file = "mods/cozy-home.pw.toml"
metafile = true

[[files]]
file = "mods/custom-splash-screen.pw.toml"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
metafile = true

[[files]]
file = "mods/default-options.pw.toml"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
metafile = true

[[files]]
file = "mods/euphoria-patches.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/fancymenu.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
metafile = true

[[files]]
file = "mods/forgiving-void.pw.toml"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/globalpacks.pw.toml"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
metafile = true

[[files]]
file = "mods/highlight.pw.toml"
metafile = true

[[files]]
file = "mods/huge-structure-blocks.pw.toml"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
metafile = true

[[files]]
file = "mods/infinite-music.pw.toml"
metafile = true

[[files]]
file = "mods/interactic.pw.toml"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
metafile = true

[[files]]
file = "mods/lenient-death.pw.toml"
metafile = true

[[files]]
file = "mods/libjf.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/lumymon.pw.toml"
metafile = true

[[files]]
file = "mods/lumyrei.pw.toml"
metafile = true

[[files]]
file = "mods/mellomons.pw.toml"
metafile = true

[[files]]
file = "mods/melody.pw.toml"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
metafile = true

[[files]]
file = "mods/moar-concrete.pw.toml"
metafile = true

[[files]]
file = "mods/mobsbegone.pw.toml"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/more-cobblemon-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/music-notification.pw.toml"
metafile = true

[[files]]
file = "mods/navas-zamega.pw.toml"
metafile = true

[[files]]
file = "mods/netherportalfix.pw.toml"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
metafile = true

[[files]]
file = "mods/notenoughcrashes.pw.toml"
metafile = true

[[files]]
file = "mods/only-bottle-caps.pw.toml"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
metafile = true

[[files]]
file = "mods/packet-fixer.pw.toml"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
metafile = true

[[files]]
file = "mods/particle-rain.pw.toml"
metafile = true

[[files]]
file = "mods/particular.pw.toml"
metafile = true

[[files]]
file = "mods/ping-wheel.pw.toml"
metafile = true

[[files]]
file = "mods/pokeblocks.pw.toml"
metafile = true

[[files]]
file = "mods/rctapi.pw.toml"
metafile = true

[[files]]
file = "mods/rctmod.pw.toml"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
metafile = true

[[files]]
file = "mods/repurposed-structures-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/resource-pack-overrides.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
metafile = true

[[files]]
file = "mods/respackopts.pw.toml"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks-(unoffical-fabric-port).pw.toml"
metafile = true

[[files]]
file = "mods/sophisticated-core-(unofficial-fabric-port).pw.toml"
metafile = true

[[files]]
file = "mods/sophisticated-storage-(unofficial-fabric-port).pw.toml"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
metafile = true

[[files]]
file = "mods/tdmon.pw.toml"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
metafile = true

[[files]]
file = "mods/tmcraft.pw.toml"
metafile = true

[[files]]
file = "mods/tooltipfix.pw.toml"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
metafile = true

[[files]]
file = "mods/villagerconfig.pw.toml"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/canon-pc-wallpapers.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/cobblemon-3d-poke-rods.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/cobblemon-classic-grass-pack.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/cobblemon-emissive-ores.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/cobblemon-interface-modded.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/cobblemon-interface.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/comforts-modernized.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/e19_cobblemon_minimap_icons.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/eeveelutions-reimagined.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/icon-xaeros-x-freshanimations.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/low-fire-pack.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/puffradio.pw.toml"
metafile = true

[[files]]
file = "resourcepacks/tras-fresh-player.pw.toml"
metafile = true

[[files]]
file = "shaderpacks/complementary-unbound.pw.toml"
metafile = true

[[files]]
file = "unsup.ini"
