name = "Cobblemon for Quinn"
author = "P1x3l101"
version = "0.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
datapack-folder = "datapacks"
no-internal-hashes = true
